# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from . import uav_pb2 as uav__pb2
except ImportError:
    import uav_pb2 as uav__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in uav_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FlightControlStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Arm = channel.unary_unary(
                '/uav.FlightControl/Arm',
                request_serializer=uav__pb2.Empty.SerializeToString,
                response_deserializer=uav__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Disarm = channel.unary_unary(
                '/uav.FlightControl/Disarm',
                request_serializer=uav__pb2.Empty.SerializeToString,
                response_deserializer=uav__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Takeoff = channel.unary_unary(
                '/uav.FlightControl/Takeoff',
                request_serializer=uav__pb2.TakeoffRequest.SerializeToString,
                response_deserializer=uav__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Land = channel.unary_unary(
                '/uav.FlightControl/Land',
                request_serializer=uav__pb2.Empty.SerializeToString,
                response_deserializer=uav__pb2.CommandReply.FromString,
                _registered_method=True)
        self.ReturnToHome = channel.unary_unary(
                '/uav.FlightControl/ReturnToHome',
                request_serializer=uav__pb2.Empty.SerializeToString,
                response_deserializer=uav__pb2.CommandReply.FromString,
                _registered_method=True)
        self.GoTo = channel.unary_unary(
                '/uav.FlightControl/GoTo',
                request_serializer=uav__pb2.Position.SerializeToString,
                response_deserializer=uav__pb2.CommandReply.FromString,
                _registered_method=True)
        self.StreamState = channel.unary_stream(
                '/uav.FlightControl/StreamState',
                request_serializer=uav__pb2.Empty.SerializeToString,
                response_deserializer=uav__pb2.UavState.FromString,
                _registered_method=True)


class FlightControlServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Arm(self, request, context):
        """基础控制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Takeoff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Land(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReturnToHome(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GoTo(self, request, context):
        """移动控制
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamState(self, request, context):
        """状态流 (Server-side streaming)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FlightControlServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Arm': grpc.unary_unary_rpc_method_handler(
                    servicer.Arm,
                    request_deserializer=uav__pb2.Empty.FromString,
                    response_serializer=uav__pb2.CommandReply.SerializeToString,
            ),
            'Disarm': grpc.unary_unary_rpc_method_handler(
                    servicer.Disarm,
                    request_deserializer=uav__pb2.Empty.FromString,
                    response_serializer=uav__pb2.CommandReply.SerializeToString,
            ),
            'Takeoff': grpc.unary_unary_rpc_method_handler(
                    servicer.Takeoff,
                    request_deserializer=uav__pb2.TakeoffRequest.FromString,
                    response_serializer=uav__pb2.CommandReply.SerializeToString,
            ),
            'Land': grpc.unary_unary_rpc_method_handler(
                    servicer.Land,
                    request_deserializer=uav__pb2.Empty.FromString,
                    response_serializer=uav__pb2.CommandReply.SerializeToString,
            ),
            'ReturnToHome': grpc.unary_unary_rpc_method_handler(
                    servicer.ReturnToHome,
                    request_deserializer=uav__pb2.Empty.FromString,
                    response_serializer=uav__pb2.CommandReply.SerializeToString,
            ),
            'GoTo': grpc.unary_unary_rpc_method_handler(
                    servicer.GoTo,
                    request_deserializer=uav__pb2.Position.FromString,
                    response_serializer=uav__pb2.CommandReply.SerializeToString,
            ),
            'StreamState': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamState,
                    request_deserializer=uav__pb2.Empty.FromString,
                    response_serializer=uav__pb2.UavState.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'uav.FlightControl', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('uav.FlightControl', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FlightControl(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Arm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uav.FlightControl/Arm',
            uav__pb2.Empty.SerializeToString,
            uav__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uav.FlightControl/Disarm',
            uav__pb2.Empty.SerializeToString,
            uav__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Takeoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uav.FlightControl/Takeoff',
            uav__pb2.TakeoffRequest.SerializeToString,
            uav__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Land(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uav.FlightControl/Land',
            uav__pb2.Empty.SerializeToString,
            uav__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReturnToHome(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uav.FlightControl/ReturnToHome',
            uav__pb2.Empty.SerializeToString,
            uav__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GoTo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/uav.FlightControl/GoTo',
            uav__pb2.Position.SerializeToString,
            uav__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/uav.FlightControl/StreamState',
            uav__pb2.Empty.SerializeToString,
            uav__pb2.UavState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
