# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: uav.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'uav.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tuav.proto\x12\x03uav\"\x07\n\x05\x45mpty\"0\n\x0c\x43ommandReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\" \n\x0eTakeoffRequest\x12\x0e\n\x06height\x18\x01 \x01(\x02\"8\n\x08Position\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\x0b\n\x03yaw\x18\x04 \x01(\x02\"\xa9\x01\n\x08UavState\x12\x12\n\nmission_id\x18\x01 \x01(\t\x12\x0c\n\x04mode\x18\x02 \x01(\t\x12\x14\n\x0c\x66light_phase\x18\x03 \x01(\t\x12\x0f\n\x07\x62\x61ttery\x18\x04 \x01(\x02\x12\x1f\n\x08position\x18\x05 \x01(\x0b\x32\r.uav.Position\x12\r\n\x05\x61rmed\x18\x06 \x01(\x08\x12\x11\n\tconnected\x18\x07 \x01(\x08\x12\x11\n\ttimestamp\x18\x08 \x01(\x03\x32\xcb\x02\n\rFlightControl\x12&\n\x03\x41rm\x12\n.uav.Empty\x1a\x11.uav.CommandReply\"\x00\x12)\n\x06\x44isarm\x12\n.uav.Empty\x1a\x11.uav.CommandReply\"\x00\x12\x33\n\x07Takeoff\x12\x13.uav.TakeoffRequest\x1a\x11.uav.CommandReply\"\x00\x12\'\n\x04Land\x12\n.uav.Empty\x1a\x11.uav.CommandReply\"\x00\x12/\n\x0cReturnToHome\x12\n.uav.Empty\x1a\x11.uav.CommandReply\"\x00\x12*\n\x04GoTo\x12\r.uav.Position\x1a\x11.uav.CommandReply\"\x00\x12,\n\x0bStreamState\x12\n.uav.Empty\x1a\r.uav.UavState\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'uav_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=18
  _globals['_EMPTY']._serialized_end=25
  _globals['_COMMANDREPLY']._serialized_start=27
  _globals['_COMMANDREPLY']._serialized_end=75
  _globals['_TAKEOFFREQUEST']._serialized_start=77
  _globals['_TAKEOFFREQUEST']._serialized_end=109
  _globals['_POSITION']._serialized_start=111
  _globals['_POSITION']._serialized_end=167
  _globals['_UAVSTATE']._serialized_start=170
  _globals['_UAVSTATE']._serialized_end=339
  _globals['_FLIGHTCONTROL']._serialized_start=342
  _globals['_FLIGHTCONTROL']._serialized_end=673
# @@protoc_insertion_point(module_scope)
